---
- name: Check if Composer is installed
  stat:
    path: /usr/local/bin/composer
  register: composer_bin

- name: Get Composer installer
  get_url:
    url: https://getcomposer.org/installer
    dest: /usr/src/composer-installer.php
  become: yes
  when: composer_bin.stat.exists == False

- name: Install Composer
  shell: php composer-installer.php
  args:
    chdir: /usr/src/
  become: yes
  when: composer_bin.stat.exists == False

- name: Add Composer to global path
  copy:
    src: /usr/src/composer.phar
    dest: /usr/local/bin/composer
    owner: root
    group: root
    mode: '0755'
    remote_src: yes
  become: yes
  when: composer_bin.stat.exists == False

- name: Cleanup composer installation
  file:
    path: "{{ item }}"
    state: absent
  with_items:
    - /usr/src/composer-installer.php
    - /usr/src/composer.phar

- name: Check if 7Zip is installed
  stat:
    path: /usr/local/bin/7z
  register: zip_bin


- name: Install 7Zip
  apt:
    name:
      p7zip-full
    state:
      present
  when: zip_bin.stat.exists == False